# Generated by Django 3.2.2 on 2021-05-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackball', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool_table',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
